import type {Metadata} from 'next';
import {Geist, JetBrains_Mono} from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const jbMono = JetBrains_Mono({
    variable: '--font-jb-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className={`${geistSans.variable} ${jbMono.variable} font-sans h-full antialiased bg-background text-foreground`}>
            <body className='min-h-full flex flex-col'>{children}</body>
        </html>
    );
}
